language: node_js
sudo: false
node_js:
    - "6"
    - "7"
    - "8"

allow_failures:
  - "8"

cache:
  directories:
    - node_modules

notifications:
  email: false

branches:
  only:
    - develop
    - master

before_script:
    - npm install

script:
  - npm run test
  - npm run test:coverage
  - codecov
  #- npm run send-cover-report

after_success:
  - bash <(curl -s https://codecov.io/bash)